import taxonomy from "@shared/labels.json";

const descriptions = [
  { scientific: "Zingiber officinale", family: "Hangat & aromatik", color: "#e8dec9", subtitle: "Kehangatan yang akrab di dapur kita.", shape: "Rimpang bercabang, beruas jelas, dengan kulit cokelat muda dan daging pucat kekuningan.", aroma: "Pedas hangat dan segar saat dipotong.", use: "Bumbu masakan, wedang, dan campuran minuman tradisional.", distinguish: "Perhatikan ruas, tekstur kulit, dan seratnya. Warna luar saja tidak cukup membedakan varietas jahe." },
  { scientific: "Zingiber officinale", family: "Hangat & aromatik", color: "#ecd4c6", subtitle: "Rimpang kecil dengan karakter yang kuat.", shape: "Varietas jahe yang umumnya lebih kecil dengan kulit bernuansa kemerahan.", aroma: "Aroma jahe dengan kesan pedas yang kuat.", use: "Bahan minuman tradisional dan bumbu.", distinguish: "Sebutan jahe merah mengacu pada varietas/kelompok budidaya, bukan spesies yang berbeda dari jahe." },
  { scientific: "Kaempferia galanga", family: "Segar & khas", color: "#dfe3d0", subtitle: "Aroma khas yang sulit digantikan.", shape: "Rimpang pendek dan membulat, kulit cokelat muda dengan daging berwarna putih.", aroma: "Tajam dan sangat khas, berbeda dari aroma jahe.", use: "Bumbu urap, seblak, dan bahan beras kencur.", distinguish: "Ukuran cenderung pendek dan gemuk. Jangan tertukar dengan temu kunci yang berbentuk jari memanjang." },
  { scientific: "Curcuma longa", family: "Kuning & berwarna", color: "#f2dca7", subtitle: "Warna keemasan, rasa yang membumi.", shape: "Rimpang beruas dengan kulit cokelat jingga; potongannya lazim berwarna kuning sampai jingga.", aroma: "Hangat, agak tanah, dengan karakter khas kunyit.", use: "Pewarna alami dan bumbu gulai, nasi kuning, serta aneka masakan.", distinguish: "Warna daging membantu pengenalan, tetapi tidak selalu terlihat dari permukaan rimpang yang masih utuh." },
  { scientific: "Curcuma zedoaria (nama rujukan)", family: "Segar & khas", color: "#e6e0cc", subtitle: "Warna lembut dengan cerita tersendiri.", shape: "Rimpang berkulit cokelat dengan daging yang lebih pucat dibanding kunyit kuning.", aroma: "Aromatik; dapat memiliki kesan mirip kamper.", use: "Dikenal dalam tradisi penggunaan rimpang setempat.", distinguish: "Nama kunyit putih dipakai untuk lebih dari satu tanaman di sejumlah daerah. Label sumber perlu dikonfirmasi dengan ahli.", review: true },
  { scientific: "Zingiber zerumbet (nama rujukan)", family: "Hangat & aromatik", color: "#e0dec6", subtitle: "Kenali lebih jauh sebelum menyimpulkan.", shape: "Rimpang beruas dengan kulit pucat hingga kecokelatan; bentuknya dapat menyerupai jahe.", aroma: "Aromatik dengan karakter yang berbeda antar jenis.", use: "Dikenal sebagai rimpang dalam pengetahuan tradisional lokal.", distinguish: "Lempuyang mencakup beberapa nama/jenis lokal. Rujukan spesies pada katalog belum memvalidasi label seluruh dataset.", review: true },
  { scientific: "Alpinia galanga", family: "Hangat & aromatik", color: "#e9dacc", subtitle: "Tekstur berserat, aroma yang tegas.", shape: "Rimpang relatif besar dan keras, dengan ruas nyata serta kulit pucat kemerahan.", aroma: "Segar, tajam dan sedikit mirip pinus.", use: "Bumbu rendang, sayur lodeh, dan aneka tumisan.", distinguish: "Umumnya lebih keras dan berserat daripada jahe. Ukuran dan warna tetap bergantung umur serta kondisi panen." },
  { scientific: "Curcuma aeruginosa", family: "Kuning & berwarna", color: "#d8ded5", subtitle: "Rimpang dengan warna bagian dalam yang unik.", shape: "Rimpang berbentuk bulat bercabang; bagian dalam dapat menunjukkan rona kebiruan atau kehijauan.", aroma: "Aromatik khas kelompok temu-temuan.", use: "Dikenal dalam penggunaan tradisional, bukan bahan untuk dikonsumsi sembarangan.", distinguish: "Temu hitam/temu ireng tidak boleh otomatis disamakan dengan semua tanaman yang disebut kunyit hitam.", review: true },
  { scientific: "Boesenbergia rotunda", family: "Segar & khas", color: "#e5d9ba", subtitle: "Ramping seperti jari, khas dalam sayur bening.", shape: "Rimpang berbentuk jari-jari memanjang yang berkumpul pada pangkal.", aroma: "Segar dan aromatik dengan karakter ringan.", use: "Bumbu sayur bening dan berbagai masakan rumahan.", distinguish: "Bentuk memanjang seperti jari membantu membedakannya dari kencur yang lebih pendek dan membulat." },
  { scientific: "Curcuma xanthorrhiza", family: "Kuning & berwarna", color: "#eed3a4", subtitle: "Salah satu kekayaan temu-temuan Nusantara.", shape: "Rimpang induk relatif besar dengan cabang; dagingnya kuning sampai jingga.", aroma: "Aromatik dengan karakter sedikit pahit.", use: "Dikenal sebagai bahan minuman dan olahan tradisional.", distinguish: "Bentuk dan ukuran membantu membedakan dari kunyit, tetapi irisan atau satu ciri visual saja tidak menjamin identitas." },
];

export const plants = taxonomy.labels.map((label, index) => ({
  ...label, ...descriptions[index],
  image: `/images/rimpang/${label.slug}.webp`,
  photo: `/images/rimpang/${label.slug}-photo.webp`,
  source: `https://powo.science.kew.org/results?q=${encodeURIComponent(descriptions[index].scientific.replace(" (nama rujukan)", ""))}`,
}));
export type Plant = (typeof plants)[number];
